[package]
name = "trace4rs-config"
version = "0.4.1"
edition = "2021"
description = "trace4rs configuration"
keywords = ["tracing", "logging", "log4rs"]
authors = ["Evan Simmons", "Everett Pompeii", "Richard Meester"]
license = "MIT"

[features]
in-order-serialization = ["serde"]

[dependencies]
literally = "0.1.3"
schemars = { version = "0.8.3", optional = true }
serde = { version = "1.0.130", optional = true, features = ["derive"] }
smart-default = "0.6.0"
thiserror = "1.0.29"
tracing = "0.1.0"
