name: Benchmark

on:
  push:
    branches: main
  pull_request_target:

env:
  CARGO_TERM_COLOR: always
  BENCHER_PROJECT: trace4rs
  BENCHER_ADAPTER: rust_criterion
  BENCHER_TESTBED: ubuntu-latest

jobs:
  benchmark_main_with_bencher:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Track main benchmarks with Bencher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bencherdev/bencher@main
      - name: Benchmark trace4rs main with Bencher
        run: |
          bencher run \
          --branch main \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          "cargo bench"

  benchmark_pr_with_bencher:
    if: github.event_name == 'pull_request_target'
    name: Track PR benchmarks with Bencher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false
      - uses: bencherdev/bencher@main
      - name: Benchmark trace4rs PR with Bencher
        run: |
          bencher run \
          --if-branch "$GITHUB_REF_NAME" \
          --else-if-branch "$GITHUB_BASE_REF" \
          --else-if-branch main \
          --github-actions "${{ secrets.GITHUB_TOKEN }}" \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          --err \
          "cargo bench"
